### ISSUE TITLE
Portrait photos created on an iPhone are shown in landscape

### ISSUE THREAD

**Issue by NielsLeenheer** [pascalw/Airplayer#6] opened 2011-01-13 20:15 UTC
Photos that are shot on my iPhone are shown in landscape by Airplayer on XBMC. Portrait photos that were shot by a real camera and synced to my iPhone are shown correctly however. Perhaps this is something that should be fixed in XBMC (reading EXIF data to determine orientation) or is it possible to fix in Airplayer?

**Comment by pascalw** [comment] 2011-01-13 20:24
I'm not sure I understand you, are all photo's shot on your iPhone displayed in landscape?

**Comment by NielsLeenheer** [comment] 2011-01-13 20:43
Yes, all photos shot on my iPhone are displayed in landscape. Both the landscape photos (correct) and the portrait photos (incorrect).

**Comment by pascalw** [comment] 2011-01-14 13:06
I'm not able to reproduce your problem. Portrait photos made with my iPhone are displayed in portrait mode like they should.

What iPhone do you have? Could you check in the EXIF data of those pictures if the orientation information is correct?

What version of XBMC are you running?

**Comment by pascalw** [comment] 2011-01-14 19:55
I noticed there's a setting in XBMC in settings->pictures to enable picture rotating based on EXIF information. Have you enabled that option?

**Comment by NielsLeenheer** [comment] 2011-01-14 21:00
I have that option turned on, but turning it off does not seem to matter. And it only happens on photos shot with the standard camera app. Photos shot with Camera+ 2 seem fine.

I think it's this XBMC bug: http://trac.xbmc.org/ticket/9843

**Comment by pascalw** [comment] 2011-01-14 21:05
Ok, then I'm closing this issue because it needs to fixed upstream.

Btw the picture attached to that ticket displays correctly in portrait mode for me. Does it for you?

**Closed as completed by pascalw** 2011-01-14 21:05 UTC
