### ISSUE TITLE
Screen is dimmed during viewing photos

### ISSUE THREAD

**Issue by NielsLeenheer** [pascalw/Airplayer#5] opened 2011-01-13 20:13 UTC
When viewing photos on XBMC from my iPhone or iPad the screens dims after a while. Moving to a different photo still works, but the screen stays dimmed. Perhaps it is possible to wake up the screen every time a new photo is being send to Airplayer.

**Comment by pascalw** [comment] 2011-01-13 20:20
Are you running the latest version?

I've implemented a fix for this a while back see c2aaf91e00b2620c25a7ec7eaa669c9241535004.

For me that fixed the problem. Basically when sending a new picture, Airplayer tries to wake up the screen by sending a "sendkey(ACTION_NONE)" command to XBMC. As far as I know there isn't a "wakup screen" command or something, but this seemed to work.

See this XBMC bug ticket too: http://trac.xbmc.org/ticket/10883.

**Comment by NielsLeenheer** [comment] 2011-01-13 20:41
Yes, I'm running the latest version. But the screen does not wake up when sending a new picture. It does wake the screen up when sending a video.

**Comment by pascalw** [comment] 2011-01-14 13:00
I'll have a look at it. It should not make any difference wether you send a picture or a movie, in both cases the ACTION_NONE command is sent and the screen should wake up.

What version of XBMC are you running?

**Comment by NielsLeenheer** [comment] 2011-01-14 21:07
I'm running the latest LiveCD with the final release of XBMC 10.

**Comment by NielsLeenheer** [comment] 2011-01-14 21:35
Okay some more information. I can reproduce the following consistantly:

1) starting with the screen dimmed
2) send the first photo from the iPhone
3) screen wakes up
4) continue sending photos
5) after a minute or two the screen is dimmed again
6) sending new photos does not wake the screen again
7) stopping airplay on the iphone
8) wait a couple of minutes, screen is still dimmed
9) start airplay again and send a new photo
10) screen wakes up again

So it appear like the ACTION_NONE command is send for the first photo and in fact works. Then the command is not send for a while and the screensaver kicks in.

**Comment by pascalw** [comment] 2011-01-15 12:08
Well, the thing is, I can't reproduce it since my XBMC doesn't even dim the screen when playing a slideshow. It only dims when a movie is paused.

But that should really matter. If you look at the log files when at step 5/6, do you see "[DEBUG] Sending wake event" messages?

Edit:
Aha. I've switched to another screensaver and now I'm able to reproduce it. After a while no wake events are sent anymore.

**Comment by pascalw** [comment] 2011-01-15 12:35
Fixed an issue where the screen wouldn&#39;t wake up when sending pictures to XBMC.

Closed by a29de8adb7e2a737a4100a1d3faeacf14d82c841.

**Closed as completed by pascalw** 2011-01-15 12:35 UTC
